In [1]:
import numpy as np

## array broadcasting
- mainly used in machine learning

In [2]:
arr1 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [3]:
arr2 = np.array([
    [13,14,15,16],
    [17,18,19,20],
    [21,22,23,24]
])

In [4]:
arr1 + arr2

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

### rules of broadcasting:
1. all shapes of arrays must be equal or same. 3X3 and 3X4 will not work, 
2. any one shape of array must be 1(either row or column) (both can be one too), 3X4 and 3X1 will work
3.

In [6]:
arr1 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
#2X4

arr2 = np.array([
    [13,14,15],
    [17,18,19],
    [21,22,23]
])
#3X3

arr1 + arr2

ValueError: operands could not be broadcast together with shapes (2,4) (3,3)

## boolean indexing
boolean indexing is conditional filtering in pandas

-

In [11]:
a = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60]
ravel_number = np.array(a)
ravel_number

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [12]:
#find all nubmer greater than 50.
filter_number = ravel_number > 50

In [13]:
ravel_number[filter_number]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [14]:
ravel_number

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [15]:
fruits = np.array(['apple','banana','coconut','apple','apple'])
fruits

array(['apple', 'banana', 'coconut', 'apple', 'apple'], dtype='<U7')

In [18]:
filter_fruits = fruits == 'apple'
fruits[filter_fruits]

array(['apple', 'apple', 'apple'], dtype='<U7')

# PANDAS

In [2]:
import pandas as pd
print("DONE")

DONE

### eda (exploratory data analysis)
  - conditional filtering
  - data cleaning
  - feature engineering
  - data analysis
  - helps to visualize data
  - data extraction

Series -> 1D 
Dataframe -> 2D

In [16]:
numbers = pd.Series([1,2,3,4,5,6], index=['A','B','C','D','E','F'])
numbers
#used for data visualization, returns the data along with index

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64

In [18]:
numbers['A':'C']

A    1
B    2
C    3
dtype: int64

In [5]:
# in python, this is needed to be done
num = [1,2,3,4,5,6]
for idx,val in enumerate(num):
    print(f'{idx}     {val}')

0     1
1     2
2     3
3     4
4     5
5     6

# DataFrame

In [15]:
personal_details = pd.DataFrame([
    ['Ram',30,'Kathmandu','Bachelors'],
    ['Shyam',30,'Bhaktapur','PHD'],
    ['Hari',30,'Lalitpur','Unqualified'],
    ['Pratim',30,'Sindupalchowk','Academics'],
    ['Niroj',30,'Palpa','Masters']
], columns = ['name','age','address','qualifications'],
    index = ['A','B','C','D','E']
)
# adding columns doesnt destroy the index though,
personal_details

     name  age        address qualifications
A     Ram   30      Kathmandu      Bachelors
B   Shyam   30      Bhaktapur            PHD
C    Hari   30       Lalitpur    Unqualified
D  Pratim   30  Sindupalchowk      Academics
E   Niroj   30          Palpa        Masters

In [17]:
personal_details[1:3]

    name  age    address qualifications
B  Shyam   30  Bhaktapur            PHD
C   Hari   30   Lalitpur    Unqualified

In [19]:
personal_details["A":]

     name  age        address qualifications
A     Ram   30      Kathmandu      Bachelors
B   Shyam   30      Bhaktapur            PHD
C    Hari   30       Lalitpur    Unqualified
D  Pratim   30  Sindupalchowk      Academics
E   Niroj   30          Palpa        Masters

In [22]:
personal_details[:"D"]

     name  age        address qualifications
A     Ram   30      Kathmandu      Bachelors
B   Shyam   30      Bhaktapur            PHD
C    Hari   30       Lalitpur    Unqualified
D  Pratim   30  Sindupalchowk      Academics

### loc and iloc
- loc ->location 
- iloc -> integer location

In [23]:

personal_details.iloc[1:3,2:]

     address qualifications
B  Bhaktapur            PHD
C   Lalitpur    Unqualified

In [24]:
personal_details.iloc[3:,0:2]

     name  age
D  Pratim   30
E   Niroj   30

In [26]:
personal_details.loc['A':'D','name':'address']

     name  age        address
A     Ram   30      Kathmandu
B   Shyam   30      Bhaktapur
C    Hari   30       Lalitpur
D  Pratim   30  Sindupalchowk

## extracting specific data example

In [28]:
personal_details.iloc[
    [1,3],
    [2,3]
]

         address qualifications
B      Bhaktapur            PHD
D  Sindupalchowk      Academics

### data read
 - csv -> read_csv
 -  excel -> read_excel
 - json -> read_json

In [9]:
import pandas as pd
df = pd.read_csv("Dataset/Employees.csv")
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [16]:
df.ndim
df.shape
df.size
#df.head()   # top 5
#df.tail()   # bottom 5
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0