In [1]:
import pandas as pd
import numpy as np
print("package installed")

package installed

In [2]:
import pandas as pd
df = pd.read_csv("Dataset/Employees.csv")
df.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='str')


notes: install  
conda install -c anaconda openpyxl

1. what are the types of data?
   - Numeric
     Discrete -> whole numbers (must start with 0)
     Continuous -> salary,weather,marks
   - Categorical
     Nominal -> category which can be compared -> eg: student grade
     Ordinal -> category which cannot be compared -> eg: color, gender
3. what are data types? int, string, float, None

In [4]:

df = pd.read_excel('Dataset/EMPLOYEES.xlsx')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0

manager_id and department_id categorical, why? they are not unique to itself
NaN -> not a number
NaT -> not a time

EDA: Exploratory Data Analysis
* understanding the data, cleaning data,
* 70% data analysis time is spent and rest we do

In [5]:
# info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    str
 2   LAST_NAME       111 non-null    str
 3   EMAIL           111 non-null    str
 4   PHONE_NUMBER    111 non-null    str
 5   HIRE_DATE       111 non-null    str
 6   JOB_ID          111 non-null    str
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), str(6)
memory usage: 9.7 KB

In [8]:
df.isnull().sum().sum()

np.int64(78)

In [14]:
#find details of employees whose salary is more than 18000
filtered_salary=df['SALARY'] > 18000
filtered_salary

0       True
1      False
2      False
3      False
4      False
       ...
106    False
107    False
108    False
109    False
110    False
Name: SALARY, Length: 111, dtype: bool

In [13]:
df[filtered_salary]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0

In [19]:
#find details of employees whose salary is in the range of 10000 and 20000, using and , between

sal_range = (df["SALARY"] >= 10000) & (df['SALARY'] <= 20000)
sal_range

sal_between = df["SALARY"].between(10000,20000)
sal_between

#if dataset is small, then using and between doesnt matter
#if dataset is large, then use and, cause between is slower 
# reasoning: and doesnt have to perform the operation but the between has to perform the operation for one condition and again for another condition

0      False
1       True
2       True
3      False
4      False
       ...
106    False
107    False
108     True
109     True
110    False
Name: SALARY, Length: 111, dtype: bool

In [20]:
df[sal_range]
df[sal_between]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,17.08.2002 00:00:00,FI_MGR,12008,NaN,101.0,100.0
14,114,Den,Raphaely,DRAPHEAL,515.127.4561,07.12.2002 00:00:00,PU_MAN,11000,NaN,100.0,30.0
45,145,John,Russell,JRUSSEL,011.44.1344.429268,01.10.2004 00:00:00,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,05.01.2005 00:00:00,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,10.03.2005 00:00:00,SA_MAN,12000,0.30,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,15.10.2007 00:00:00,SA_MAN,11000,0.30,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,29.01.2008 00:00:00,SA_MAN,10500,0.20,100.0,80.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,30.01.2005 00:00:00,SA_REP,10000,0.30,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,30.01.2004 00:00:00,SA_REP,10000,0.35,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,11.11.2005 00:00:00,SA_REP,10500,0.25,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,11.03.2005 00:00:00,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,23.03.2006 00:00:00,SA_REP,10000,0.20,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,11.05.2004 00:00:00,SA_REP,11000,0.30,149.0,80.0
101,201,Michael,Hartstein,MHARTSTE,515.123.5555,17.02.2004 00:00:00,MK_MAN,13000,NaN,100.0,20.0
104,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
108,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0

In [24]:
#categorical data: use OR ok !!! ;)
#find details of employees who works in job SA_REP, IT_PROG

job_details = (df['JOB_ID'] == 'SA_REP') | (df['JOB_ID'] == 'IT_PROG')
df[job_details]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,25.06.2005 00:00:00,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,05.02.2006 00:00:00,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,07.02.2007 00:00:00,IT_PROG,4200,NaN,103.0,60.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,30.01.2005 00:00:00,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,24.03.2005 00:00:00,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,20.08.2005 00:00:00,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,30.03.2006 00:00:00,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,09.12.2006 00:00:00,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,23.11.2007 00:00:00,SA_REP,7000,0.15,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,30.01.2004 00:00:00,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,04.03.2004 00:00:00,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,01.08.2004 00:00:00,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,10.03.2005 00:00:00,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,15.12.2005 00:00:00,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,03.11.2006 00:00:00,SA_REP,7000,0.25,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,11.11.2005 00:00:00,SA_REP,10500,0.25,147.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,19.03.2007 00:00:00,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,24.01.2008 00:00:00,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,23.02.2008 00:00:00,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,24.03.2008 00:00:00,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,21.04.2008 00:00:00,SA_REP,6200,0.10,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,11.03.2005 00:00:00,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,23.03.2006 00:00:00,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,24.01.2006 00:00:00,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,23.02.2007 00:00:00,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,24.03.2007 00:00:00,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,21.04.2008 00:00:00,SA_REP,6100,0.10,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,11.05.2004 00:00:00,SA_REP,11000,0.30,149.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,19.03.2005 00:00:00,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,24.03.2006 00:00:00,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,23.04.2006 00:00:00,SA_REP,8400,0.20,149.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,24.05.2007 00:00:00,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,04.01.2008 00:00:00,SA_REP,6200,0.10,149.0,80.0

In [28]:
#categorical data: use OR ok !!! ;)
#find details of employees who works in job SA_REP, IT_PROG using isin

job_det = df['JOB_ID'].isin(['SA_REP','IT_PROG']) # if we are calling the function, we have to use list in the parameters if we have multiple values to pass
df[job_det]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,25.06.2005 00:00:00,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,05.02.2006 00:00:00,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,07.02.2007 00:00:00,IT_PROG,4200,NaN,103.0,60.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,30.01.2005 00:00:00,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,24.03.2005 00:00:00,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,20.08.2005 00:00:00,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,30.03.2006 00:00:00,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,09.12.2006 00:00:00,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,23.11.2007 00:00:00,SA_REP,7000,0.15,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,30.01.2004 00:00:00,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,04.03.2004 00:00:00,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,01.08.2004 00:00:00,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,10.03.2005 00:00:00,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,15.12.2005 00:00:00,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,03.11.2006 00:00:00,SA_REP,7000,0.25,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,11.11.2005 00:00:00,SA_REP,10500,0.25,147.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,19.03.2007 00:00:00,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,24.01.2008 00:00:00,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,23.02.2008 00:00:00,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,24.03.2008 00:00:00,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,21.04.2008 00:00:00,SA_REP,6200,0.10,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,11.03.2005 00:00:00,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,23.03.2006 00:00:00,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,24.01.2006 00:00:00,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,23.02.2007 00:00:00,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,24.03.2007 00:00:00,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,21.04.2008 00:00:00,SA_REP,6100,0.10,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,11.05.2004 00:00:00,SA_REP,11000,0.30,149.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,19.03.2005 00:00:00,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,24.03.2006 00:00:00,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,23.04.2006 00:00:00,SA_REP,8400,0.20,149.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,24.05.2007 00:00:00,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,04.01.2008 00:00:00,SA_REP,6200,0.10,149.0,80.0

In [30]:
# find details of employees whose salary is in range of 6000 to 10000 and they must be working on job SA_REP

# using and condition
emp_detail1 = (df["SALARY"] >= 6000) & (df['SALARY'] <= 10000) & (df['JOB_ID'] == "SA_REP")
df[emp_detail1]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,30.01.2005 00:00:00,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,24.03.2005 00:00:00,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,20.08.2005 00:00:00,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,30.03.2006 00:00:00,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,09.12.2006 00:00:00,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,23.11.2007 00:00:00,SA_REP,7000,0.15,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,30.01.2004 00:00:00,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,04.03.2004 00:00:00,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,01.08.2004 00:00:00,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,10.03.2005 00:00:00,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,15.12.2005 00:00:00,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,03.11.2006 00:00:00,SA_REP,7000,0.25,146.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,19.03.2007 00:00:00,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,24.01.2008 00:00:00,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,23.02.2008 00:00:00,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,24.03.2008 00:00:00,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,21.04.2008 00:00:00,SA_REP,6200,0.10,147.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,23.03.2006 00:00:00,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,24.01.2006 00:00:00,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,23.02.2007 00:00:00,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,24.03.2007 00:00:00,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,21.04.2008 00:00:00,SA_REP,6100,0.10,148.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,19.03.2005 00:00:00,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,24.03.2006 00:00:00,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,23.04.2006 00:00:00,SA_REP,8400,0.20,149.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,24.05.2007 00:00:00,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,04.01.2008 00:00:00,SA_REP,6200,0.10,149.0,80.0

In [32]:
# using between and isin
emp_detail2 = df["SALARY"].between(6000,10000) & df['JOB_ID'].isin(['SA_REP'])
df[emp_detail2]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,30.01.2005 00:00:00,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,24.03.2005 00:00:00,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,20.08.2005 00:00:00,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,30.03.2006 00:00:00,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,09.12.2006 00:00:00,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,23.11.2007 00:00:00,SA_REP,7000,0.15,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,30.01.2004 00:00:00,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,04.03.2004 00:00:00,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,01.08.2004 00:00:00,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,10.03.2005 00:00:00,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,15.12.2005 00:00:00,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,03.11.2006 00:00:00,SA_REP,7000,0.25,146.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,19.03.2007 00:00:00,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,24.01.2008 00:00:00,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,23.02.2008 00:00:00,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,24.03.2008 00:00:00,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,21.04.2008 00:00:00,SA_REP,6200,0.10,147.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,23.03.2006 00:00:00,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,24.01.2006 00:00:00,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,23.02.2007 00:00:00,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,24.03.2007 00:00:00,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,21.04.2008 00:00:00,SA_REP,6100,0.10,148.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,19.03.2005 00:00:00,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,24.03.2006 00:00:00,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,23.04.2006 00:00:00,SA_REP,8400,0.20,149.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,24.05.2007 00:00:00,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,04.01.2008 00:00:00,SA_REP,6200,0.10,149.0,80.0

In [ ]:
#pandas group by study