#### data cleaning 
     - null value cleaning
     - remove unwanted data or white spaces

In [1]:
import pandas as pd
import numpy as np
print("package imported")

package imported

In [32]:
df = pd.read_csv("Dataset/Employees.csv")
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    str
 2   LAST_NAME       111 non-null    str
 3   EMAIL           111 non-null    str
 4   PHONE_NUMBER    111 non-null    str
 5   HIRE_DATE       111 non-null    str
 6   JOB_ID          111 non-null    str
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), str(6)
memory usage: 9.7 KB

In [34]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

## handling null (NaN) values
1. Fill data
   - mean  (numeric record) -> if data is in range fill with mean value
   - median  (numeric record) -> if data is not in range fill with median value
   - mode  (categorical record)
   - custom record  (both numeric and categorical)
3. Drop Row/Column

In [35]:
commission_mean = round(df['COMMISSION_PCT'].mean(),2)
# df['COMMISSION_PCT'].fillna(commission_mean, inplace = True)

In [36]:
df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(commission_mean)
print('commission pct is filled with mean value')

commission pct is filled with mean value

In [37]:
df['COMMISSION_PCT'].median()

np.float64(0.22)

In [38]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,0.22,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0

In [51]:
manager_mode = df['MANAGER_ID'].mode()[0]
manager_mode

np.float64(100.0)

In [52]:
department_mode = df['DEPARTMENT_ID'].mode()[0]
department_mode

np.float64(50.0)

In [53]:
df["MANAGER_ID"]=df["MANAGER_ID"].fillna(manager_mode)
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].fillna(department_mode)

In [54]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,0.22,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0

In [55]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

## To add custom record
- add the record in fillna("your data here") 
- df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(0)  -> we are using to fill our own data

In [56]:
df['COMMISSION_PCT'].unique()

array([0.22, 0.4 , 0.3 , 0.2 , 0.25, 0.15, 0.35, 0.1 ])

In [57]:
df['COMMISSION_PCT'].value_counts()

COMMISSION_PCT
0.22    76
0.30     7
0.20     7
0.25     6
0.10     6
0.15     5
0.35     3
0.40     1
Name: count, dtype: int64

### Drop data

In [71]:
df = pd.read_csv("Dataset/Employees.csv")
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [72]:
# default -> row wise delete
#df.dropna(inplace=True) # doesnt remove in original df, so use inplace=True
df = df.dropna(axis=1) # you can use this too
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000
...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300

#### parameters of dropna()
- (axis = 0 (default)) -> Row and (axis = 1) -> Column
- how = any(default)/all
- inplace = False(default)/True